source_directory: 'Assets/'
actions:
  - source_file: 'data.json'
  - source_file: 'data.json'
    json_destination_file: 'data_mod.json'
  - source_file: 'data_mod.json'
    yaml_destination_file: 'data_mod.yaml'
    use_object: True
  - source_file: 'data_mod.json'
    yaml_destination_file: 'data_mod2.yaml'
    use_object: False
  - source_file: 'data.json'
    json_destination_file: 'data_mod2.json'
