source_directory: 'Assets/'
actions:
  - type: 'json_stats'
    source: 'data.json'
  - type: 'json_select'
    source: 'data.json'
    destination: 'data_mod.json'
  - type: 'json_object_convert_to_yaml'
    source: 'data_mod.json'
    destination: 'data_mod.yaml'
  - type: 'json_path_convert_to_yaml'
    source: 'data_mod.json'
    destination: 'data_mod2.yaml'
  - type: 'json_select'
    source: 'data.json'
    destination: 'data_mod2.json'
